---
- hosts: all
  become: true
  pre_tasks:

  - name: Update repository Index (CentOS)
    tags: always
    yum:
      name: "*"
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"

  - name: Update repo index (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"
  
  - name: MOTD
    copy:
      content: "Ansible managed by Magnait \n"
      dest: /etc/motd

- hosts: all
  become: true
  roles:
      - promentheus
      - apache2

